version: '3.9'
services:
  app:
    container_name: golang_container
    environment:
      - POSTGRES_USER=$(DB_USER)
      - POSTGRES_PASSWORD=$(DB_PASS)
      - POSTGRES_DB=$(DB_NAME)
      - DATABASE_HOST=$(DB_HOST)
      - DATABASE_PORT=$(DB_PORT)
    tty: true
    build: .
    ports:
      - 8000:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - chat

  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '1234:5432'
    networks:
      - chat

networks:
  chat:
    driver: bridge
